auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: zeimi33's Blog”
title: zeimi33's blog
description: 人生何处不相逢
url: http://zeimi33.github.io
feed: /atom.xml
author_info: <a href="http://zeimi33.github.io/">zeimi33</a>
