auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Hyper Hamster
url: http://zemi33.github.io
feed: /atom.xml
author_info: <a href="http://zeimi33.github.io/">zeimi33</a>
